services:
  db:
    image: postgres:15-alpine
    container_name: sinaliza-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: sinaliza-postgres
      POSTGRES_PASSWORD: sinaliza-postgres
      POSTGRES_DB: sinaliza-db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U sinaliza-postgres -d sinaliza-db"]
      interval: 10s
      timeout: 5s
      retries: 5
